/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostResponse = IDL.Record({ 'ok' : IDL.Bool, 'postId' : IDL.Nat });
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const PostRecord = IDL.Record({
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'authorId' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'likes' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'authorDisplayName' : IDL.Text,
  'postId' : IDL.Nat,
});
export const UserProfilePublic = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : IDL.Nat,
  'joinedAt' : IDL.Int,
});
export const LoginResponse = IDL.Record({
  'ok' : IDL.Bool,
  'displayName' : IDL.Text,
  'userId' : IDL.Nat,
  'message' : IDL.Text,
});
export const RegistrationResponse = IDL.Record({
  'ok' : IDL.Bool,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeUserPassword' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PostResponse],
      [],
    ),
  'deleteInquiry' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'getAllCommunityUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'username' : IDL.Text,
            'displayName' : IDL.Text,
            'userId' : IDL.Nat,
            'joinedAt' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllInquiriesSortedByDestination' : IDL.Func(
      [],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalMembers' : IDL.Nat, 'totalPosts' : IDL.Nat })],
      ['query'],
    ),
  'getInquiriesByDestination' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiry' : IDL.Func([IDL.Text], [Inquiry], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(PostRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'ok' : IDL.Bool, 'likes' : IDL.Nat })],
      [],
    ),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResponse], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [RegistrationResponse],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostResponse = IDL.Record({ 'ok' : IDL.Bool, 'postId' : IDL.Nat });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const PostRecord = IDL.Record({
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'authorId' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'likes' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'authorDisplayName' : IDL.Text,
    'postId' : IDL.Nat,
  });
  const UserProfilePublic = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : IDL.Nat,
    'joinedAt' : IDL.Int,
  });
  const LoginResponse = IDL.Record({
    'ok' : IDL.Bool,
    'displayName' : IDL.Text,
    'userId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const RegistrationResponse = IDL.Record({
    'ok' : IDL.Bool,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeUserPassword' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PostResponse],
        [],
      ),
    'deleteInquiry' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'getAllCommunityUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'displayName' : IDL.Text,
              'userId' : IDL.Nat,
              'joinedAt' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllInquiriesSortedByDestination' : IDL.Func(
        [],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalMembers' : IDL.Nat, 'totalPosts' : IDL.Nat })],
        ['query'],
      ),
    'getInquiriesByDestination' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Text], [Inquiry], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(PostRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'ok' : IDL.Bool, 'likes' : IDL.Nat })],
        [],
      ),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResponse], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [RegistrationResponse],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };