/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminProfile { 'principal' : string, 'username' : string }
export interface Inquiry {
  'id' : string,
  'destination' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface LoginResponse {
  'ok' : boolean,
  'displayName' : string,
  'userId' : bigint,
  'message' : string,
}
export interface PostRecord {
  'title' : string,
  'destination' : string,
  'authorId' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'likes' : bigint,
  'imageUrl' : string,
  'authorDisplayName' : string,
  'postId' : bigint,
}
export interface PostResponse { 'ok' : boolean, 'postId' : bigint }
export interface RegistrationResponse { 'ok' : boolean, 'message' : string }
export interface SessionResponse {
  'ok' : boolean,
  'token' : SessionToken,
  'message' : string,
}
export type SessionToken = string;
export type Time = bigint;
export interface UserProfile { 'bio' : string, 'displayName' : string }
export interface UserProfilePublic {
  'bio' : string,
  'displayName' : string,
  'userId' : bigint,
  'joinedAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeUserPassword' : ActorMethod<[bigint, string, string], boolean>,
  'createPost' : ActorMethod<
    [bigint, string, string, string, string, string],
    PostResponse
  >,
  'deleteInquiry' : ActorMethod<[string, [] | [string]], undefined>,
  'deletePost' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'getAllCommunityUsers' : ActorMethod<
    [],
    Array<
      {
        'username' : string,
        'displayName' : string,
        'userId' : bigint,
        'joinedAt' : bigint,
      }
    >
  >,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllInquiriesSortedByDestination' : ActorMethod<[], Array<Inquiry>>,
  'getAllPosts' : ActorMethod<[], Array<PostRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityStats' : ActorMethod<
    [],
    { 'totalMembers' : bigint, 'totalPosts' : bigint }
  >,
  'getInquiriesByDestination' : ActorMethod<[string], Array<Inquiry>>,
  'getInquiry' : ActorMethod<[string], Inquiry>,
  'getPostsByUser' : ActorMethod<[bigint], Array<PostRecord>>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[bigint], [] | [UserProfilePublic]>,
  'isAdminSession' : ActorMethod<[SessionToken], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], { 'ok' : boolean, 'likes' : bigint }>,
  'loginAdmin' : ActorMethod<[string, string], SessionResponse>,
  'loginUser' : ActorMethod<[string, string], LoginResponse>,
  'registerAdmin' : ActorMethod<[string, string], AdminProfile>,
  'registerUser' : ActorMethod<
    [string, string, string, boolean],
    RegistrationResponse
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];